# Generated by Django 6.0.6 on 2026-06-24 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "default_related_name": "%(class)s",
                "ordering": ["-pub_date"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "default_related_name": "%(class)s",
                "ordering": ["-pub_date"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(2026)],
                verbose_name="Год выпуска",
            ),
        ),
    ]
